// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flexContentsBox': string;
  'flexContentsBox__button': string;
  'flexContentsBox__images': string;
  'flexContentsBox__input': string;
}
export const cssExports: CssExports;
export default cssExports;
